namespace CrescentCompass.Core;

/// <summary>Only the single-command macros generated by this plugin are eligible for automatic icon updates.</summary>
public static class PhantomMacroIcons
{
    public const uint DefaultIcon = 66001; // TC MacroIcon row 0.

    public static PhantomJob? Match(IEnumerable<string> lines)
    {
        var nonEmpty = lines.Where(line => !string.IsNullOrWhiteSpace(line)).Take(2).ToArray();
        if (nonEmpty.Length != 1) return null;
        var parts = nonEmpty[0].Trim().Split((char[]?)null, 3, StringSplitOptions.RemoveEmptyEntries);
        if (parts.Length != 3 || !parts[0].Equals("/crescent", StringComparison.OrdinalIgnoreCase) ||
            !parts[1].Equals("job", StringComparison.OrdinalIgnoreCase)) return null;
        return PhantomJobs.Resolve(parts[2]);
    }

    public static uint? Replacement(uint currentIcon, IEnumerable<string> lines)
    {
        // Preserve a user's chosen icon. An old phantom icon may follow an edited job command.
        if (currentIcon != DefaultIcon && !PhantomJobs.All.Any(job => job.IconId == currentIcon)) return null;
        var job = Match(lines);
        return job is not null && currentIcon != job.IconId ? job.IconId : null;
    }
}
