<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <PlatformTarget>x64</PlatformTarget>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../CrescentCompass.Core/CrescentCompass.Core.csproj" />
    <Compile Include="../../CrescentCompass/Ui/*.cs" Link="Ui/%(Filename)%(Extension)" />
    <Reference Include="Dalamud.Bindings.ImGui"><HintPath>../../.sdk/Dalamud.Bindings.ImGui.dll</HintPath></Reference>
    <Reference Include="HexaGen.Runtime"><HintPath>../../.sdk/HexaGen.Runtime.dll</HintPath></Reference>
    <None Include="../../CrescentCompass/Data/loot_catalog.json" Link="loot_catalog.json" CopyToOutputDirectory="PreserveNewest" />
    <None Include="../../.sdk/cimgui.dll" Link="cimgui.dll" CopyToOutputDirectory="PreserveNewest" />
    <None Include="../../CrescentCompass/Data/SouthHorn/carrot_locations.json" Link="carrot_locations.json" CopyToOutputDirectory="PreserveNewest" />
    <None Include="../../CrescentCompass/Data/SouthHorn/treasure_locations.json" Link="treasure_locations.json" CopyToOutputDirectory="PreserveNewest" />
    <None Include="../../CrescentCompass/Data/SouthHorn/treasure_route.json" Link="treasure_route.json" CopyToOutputDirectory="PreserveNewest" />
    <None Include="../../CrescentCompass/Data/SouthHorn/precomputed_treasure_hunt_data.json" Link="precomputed_treasure_hunt_data.json" CopyToOutputDirectory="PreserveNewest" />
    <None Include="../../CrescentCompass/Data/SouthHorn/exploration_locations.json" Link="exploration_locations.json" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
